server:
  servlet:
    context-path: /api

# Application config

spring:
  profiles:
    active: @active.profile@

shop:
  strategy: @strategy@

---

spring:
  profiles: dev
  datasource:
    url: jdbc:h2:~/db/app_data
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    enabled: true
    baseline-on-migrate: true
    check-location: true

---

spring:
  profiles: with-basic
  datasource:
    url: jdbc:h2:~/db/app_data
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    enabled: true
    baseline-on-migrate: true
    check-location: true

---

spring:
  profiles: with-form
  datasource:
    url: jdbc:h2:~/db/app_data
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    enabled: true
    baseline-on-migrate: true
    check-location: true

---

spring:
  profiles: unit-test
  jdbc:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testDb;DB_CLOSE_DELAY=-1
  datasource:
    url: jdbc:h2:~/db/app_data
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true

---

spring:
  profiles: integration-test
  jdbc:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testDb;DB_CLOSE_DELAY=-1
  datasource:
    url: jdbc:h2:~/db/app_data
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true